<a href="https://colab.research.google.com/github/placemedas/Python-Learner-Toolkit---DataScience/blob/master/Numpy_Beginners_Guide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Creation of Arrays with different dimension

In [ ]:
my1DArray = np.array([1,8,4,6])
print(my1DArray)

[1 8 4 6]


In [ ]:
my2DArray = np.array([[1,8,4,6],[2,4,9,16],[3,5,10,17]])
print(my2DArray)

[[ 1  8  4  6]
 [ 2  4  9 16]
 [ 3  5 10 17]]


In [ ]:
my3DArray = np.array([[[1,2,3,4],[4,5,6,7]],[[3,6,7,8],[9,8,7,6]]])
print(my3DArray)

[[[1 2 3 4]
  [4 5 6 7]]

 [[3 6 7 8]
  [9 8 7 6]]]


In [ ]:
print(my2DArray.data)

In [ ]:
print(my2DArray.shape)

(3, 4)


In [ ]:
print(my2DArray.dtype)

int64


In [ ]:
print(my2DArray.strides)

(32, 8)


In [ ]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
zeros = np.zeros((3,4),dtype=np.int64)
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
np.random.random((2,2))

array([[0.51888653, 0.69401205],
       [0.972346  , 0.32264808]])

In [ ]:
emptyArray = np.empty((3,2))
print(emptyArray)

[[3.33399055e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [ ]:
fullArray = np.full((2,2),7)
print(fullArray)

[[7 7]
 [7 7]]


In [ ]:
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

[10 15 20]


In [ ]:
  evenSpacedArray2 = np.linspace(0,2,9)
  print(evenSpacedArray2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
#Save a numpy array to a file
x = np.arange(0.0,50.0,1)
np.savetxt('data.out',x,delimiter = ',')

In [ ]:
# Load numpy array from text
z = np.loadtxt('data.out',unpack = True)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [ ]:
# Loading numpy array using genfromtxt method
my_array2 = np.genfromtxt('data.out',skip_header=1,filling_values=-999)
print(my_array2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [ ]:
#Print the number of my2DArray's dimensions
print(my2DArray.ndim)

2


In [ ]:
#Print the number of my2DArray's elements
print(my2DArray.size)

12


In [ ]:
#Print information about my2DArray's memory layout
print(my2DArray.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
#Print the length of one array element in bytes
print(my2DArray.itemsize)

8


In [ ]:
# Print the total consumed bytes by my2DArray
print(my2DArray.nbytes)

96


Addition of two numpy arrays with same shape is possible. Example below

In [ ]:
A = np.ones((6,8))
print(A.shape)

(6, 8)


In [ ]:
B = np.random.random((6,8))
print(B.shape)

(6, 8)


In [ ]:
print(A + B)

[[1.72807851 1.7941149  1.98890533 1.19315093 1.2400251  1.73764322
  1.97934201 1.66884834]
 [1.22242052 1.32889086 1.49553694 1.70886645 1.46587158 1.1941176
  1.06076101 1.28692383]
 [1.43367694 1.07607659 1.89912029 1.43555642 1.00016091 1.48445031
  1.15852539 1.07651448]
 [1.73888888 1.10679798 1.88510722 1.54655913 1.34481152 1.58537967
  1.14390843 1.1403376 ]
 [1.54139318 1.61932076 1.68081315 1.55368685 1.31817841 1.69282729
  1.87735715 1.59345449]
 [1.3215482  1.96283568 1.19920478 1.59852762 1.18086503 1.72163011
  1.901793   1.85327495]]


Two dimensions are compatible when one of the dimension is 1. Example below


In [ ]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(x.shape)

(3, 4)


In [ ]:
y = np.arange(4)
print(y)

[0 1 2 3]


In [ ]:
print(x-y)

[[ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]
 [ 1.  0. -1. -2.]]


### Arrays can be broadcast together if they are compatible in all dimensions. Example below

Note:  Changing y to (10,2,8) or (10,1,4) will cause value error as the dimensions change making it incompatible

In [ ]:
x = np.ones((6,8))
y = np.random.random((10,1,8))
print(x)
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[[0.2367109  0.40783628 0.43705158 0.95941133 0.30396633 0.33568431
   0.4659453  0.9149195 ]]

 [[0.18500631 0.81964703 0.75406446 0.21021213 0.28419889 0.27182936
   0.35994741 0.92807325]]

 [[0.01670343 0.41183131 0.06597421 0.77816548 0.09885523 0.82589396
   0.98588323 0.17644358]]

 [[0.28999869 0.70300155 0.07904112 0.46848181 0.04386905 0.93342991
   0.28140514 0.68741404]]

 [[0.22632273 0.16921891 0.07578576 0.02243767 0.54411172 0.68991001
   0.18811562 0.98960929]]

 [[0.42279218 0.33367734 0.58001263 0.52498877 0.1233168  0.58589799
   0.3778712  0.95750019]]

 [[0.66247568 0.48506418 0.98799223 0.27188458 0.74658105 0.88241361
   0.61595217 0.19911165]]

 [[0.13134421 0.86313994 0.59387891 0.82174547 0.20193765 0.95103683
   0.33142588 0.5647512 ]]

 [[0.64018331 0.52631332 0.78973098 0.00780132 0.71887352 0.3

In [ ]:
print(x+y)

[[[1.2367109  1.40783628 1.43705158 1.95941133 1.30396633 1.33568431
   1.4659453  1.9149195 ]
  [1.2367109  1.40783628 1.43705158 1.95941133 1.30396633 1.33568431
   1.4659453  1.9149195 ]
  [1.2367109  1.40783628 1.43705158 1.95941133 1.30396633 1.33568431
   1.4659453  1.9149195 ]
  [1.2367109  1.40783628 1.43705158 1.95941133 1.30396633 1.33568431
   1.4659453  1.9149195 ]
  [1.2367109  1.40783628 1.43705158 1.95941133 1.30396633 1.33568431
   1.4659453  1.9149195 ]
  [1.2367109  1.40783628 1.43705158 1.95941133 1.30396633 1.33568431
   1.4659453  1.9149195 ]]

 [[1.18500631 1.81964703 1.75406446 1.21021213 1.28419889 1.27182936
   1.35994741 1.92807325]
  [1.18500631 1.81964703 1.75406446 1.21021213 1.28419889 1.27182936
   1.35994741 1.92807325]
  [1.18500631 1.81964703 1.75406446 1.21021213 1.28419889 1.27182936
   1.35994741 1.92807325]
  [1.18500631 1.81964703 1.75406446 1.21021213 1.28419889 1.27182936
   1.35994741 1.92807325]
  [1.18500631 1.81964703 1.75406446 1.21021213 1

### Basic Operations on Numpy array

In [ ]:
x = np.array([[1,2,3],[2,3,4]])
y = np.array([[1,4,9],[2,5,10]])
add = np.add(x, y)
print(add)

[[ 2  6 12]
 [ 4  8 14]]


In [ ]:
sub = np.subtract(x,y)
print(sub)

[[ 0 -2 -6]
 [ 0 -2 -6]]


In [ ]:
mul = np.multiply(x,y)
print(mul)

[[ 1  8 27]
 [ 4 15 40]]


In [ ]:
div = np.divide(x,y)
print(div)

[[1.         0.5        0.33333333]
 [1.         0.6        0.4       ]]


In [ ]:
rem = np.remainder(x,y)
print(rem)

[[0 2 3]
 [0 3 4]]


### Create a subset and slice an array using an index

In [ ]:
x = np.array([10,20,30,40,50])
print(x)
#Select items at indices 0 and 1
print(x[0:2])

[10 20 30 40 50]
[10 20]


In [ ]:
#Select items at rows 0 and 1 and column 1 from 2D array
y = np.array([[1,2,3,4],[9,10,11,12]])
print(y[0:2, 1])

[ 2 10]


In [ ]:
biggerThan2 = (y >= 2)
print(y[biggerThan2])

[ 2  3  4  9 10 11 12]
